### ISSUE TITLE
Duplicate code in `use-digraph.ts`

### ISSUE THREAD

**Issue by nagasawaryoya** [ts-graphviz/react#261]
**Is your feature request related to a problem? Please describe.**
Duplicate code in `use-digraph.ts`.

**Describe the solution you'd like**
Remove the duplicate code and add a test to make sure it's okay.

**Additional context**
![use-digraph_ts_—_react](https://user-images.githubusercontent.com/53528726/109723938-2223b680-7bf2-11eb-807f-ab4205ef7852.png)

**Comment by kamiazya** [comment]
Close it because it has been left for a long time and the temperature is not high.

Open it again when needed.
